<?php

/**
 * This is the model base class for the table "compra".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Compra".
 *
 * Columns in table "compra" available as properties of the model,
 * followed by relations of table "compra" available as properties of the model.
 *
 * @property integer $id_compra
 * @property integer $id_proveedor
 * @property integer $id_usuario
 * @property double $total_compra
 * @property string $fecha_compra
 * @property string $observaciones
 *
 * @property Proveedor $idProveedor
 * @property Usuario $idUsuario
 * @property DetalleCompra[] $detalleCompras
 */
abstract class BaseCompra extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'compra';
    }

    public static function representingColumn() {
        return 'id_compra';
    }

    public function rules() {
        return array(
            // array('id_compra', 'required'),
            array('id_compra, id_proveedor, id_usuario', 'numerical', 'integerOnly'=>true),
            array('total_compra', 'numerical'),
            array('fecha_compra, observaciones', 'safe'),
            array('id_proveedor, id_usuario, total_compra, fecha_compra, observaciones', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_compra, id_proveedor, id_usuario, total_compra, fecha_compra, observaciones', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'idProveedor' => array(self::BELONGS_TO, 'Proveedor', 'id_proveedor'),
            'idUsuario' => array(self::BELONGS_TO, 'Usuario', 'id_usuario'),
            'detalleCompras' => array(self::HAS_MANY, 'DetalleCompra', 'id_compra'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_compra' => Yii::t('app', 'Id Compra'),
                'id_proveedor' => Yii::t('app', 'Id Proveedor'),
                'id_usuario' => Yii::t('app', 'Id Usuario'),
                'total_compra' => Yii::t('app', 'Total Compra'),
                'fecha_compra' => Yii::t('app', 'Fecha Compra'),
                'observaciones' => Yii::t('app', 'Observaciones'),
                'idProveedor' => null,
                'idUsuario' => null,
                'detalleCompras' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_compra', $this->id_compra);
        $criteria->compare('id_proveedor', $this->id_proveedor);
        $criteria->compare('id_usuario', $this->id_usuario);
        $criteria->compare('total_compra', $this->total_compra);
        $criteria->compare('fecha_compra', $this->fecha_compra, true);
        $criteria->compare('observaciones', $this->observaciones, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}