<?php

/**
 * This is the model base class for the table "producto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Producto".
 *
 * Columns in table "producto" available as properties of the model,
 * followed by relations of table "producto" available as properties of the model.
 *
 * @property integer $id_producto
 * @property string $nombre_producto
 * @property integer $stock
 * @property double $costo_actual
 * @property double $precio
 * @property string $presentacion
 *
 * @property DetalleCompra[] $detalleCompras
 */
abstract class BaseProducto extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'producto';
    }

    public static function representingColumn() {
        return 'nombre_producto';
    }

    public function rules() {
        return array(
            // array('id_producto', 'required'),
            array('id_producto, stock', 'numerical', 'integerOnly'=>true),
            array('costo_actual, precio', 'numerical'),
            array('nombre_producto, presentacion', 'length', 'max'=>50),
            array('nombre_producto, stock, costo_actual, precio, presentacion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_producto, nombre_producto, stock, costo_actual, precio, presentacion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'detalleCompras' => array(self::HAS_MANY, 'DetalleCompra', 'id_producto'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_producto' => Yii::t('app', 'Id Producto'),
                'nombre_producto' => Yii::t('app', 'Nombre Producto'),
                'stock' => Yii::t('app', 'Stock'),
                'costo_actual' => Yii::t('app', 'Costo Actual'),
                'precio' => Yii::t('app', 'Precio'),
                'presentacion' => Yii::t('app', 'Presentacion'),
                'detalleCompras' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_producto', $this->id_producto);
        $criteria->compare('nombre_producto', $this->nombre_producto, true);
        $criteria->compare('stock', $this->stock);
        $criteria->compare('costo_actual', $this->costo_actual);
        $criteria->compare('precio', $this->precio);
        $criteria->compare('presentacion', $this->presentacion, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}