<?php

/**
 * This is the model base class for the table "usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "usuario" available as properties of the model,
 * followed by relations of table "usuario" available as properties of the model.
 *
 * @property integer $id_usuario
 * @property string $nombre_usuario
 * @property string $username_usuario
 * @property string $clave_usuario
 * @property string $email_usuario
 * @property string $nombre_tienda
 * @property string $informacion_tienda
 *
 * @property Compra[] $compras
 */
abstract class BaseUsuario extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'usuario';
    }

    public static function representingColumn() {
        return 'nombre_usuario';
    }

    public function rules() {
        return array(
            array('nombre_usuario, username_usuario, clave_usuario', 'required'),
            array('nombre_usuario, username_usuario, clave_usuario, email_usuario', 'length', 'max'=>50),
            array('nombre_tienda', 'length', 'max'=>255),
            array('informacion_tienda', 'safe'),
            array('email_usuario, nombre_tienda, informacion_tienda', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_usuario, nombre_usuario, username_usuario, clave_usuario, email_usuario, nombre_tienda, informacion_tienda', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'compras' => array(self::HAS_MANY, 'Compra', 'id_usuario'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_usuario' => Yii::t('app', 'Id Usuario'),
                'nombre_usuario' => Yii::t('app', 'Nombre Usuario'),
                'username_usuario' => Yii::t('app', 'Username Usuario'),
                'clave_usuario' => Yii::t('app', 'Clave Usuario'),
                'email_usuario' => Yii::t('app', 'Email Usuario'),
                'nombre_tienda' => Yii::t('app', 'Nombre Tienda'),
                'informacion_tienda' => Yii::t('app', 'Informacion Tienda'),
                'compras' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_usuario', $this->id_usuario);
        $criteria->compare('nombre_usuario', $this->nombre_usuario, true);
        $criteria->compare('username_usuario', $this->username_usuario, true);
        $criteria->compare('clave_usuario', $this->clave_usuario, true);
        $criteria->compare('email_usuario', $this->email_usuario, true);
        $criteria->compare('nombre_tienda', $this->nombre_tienda, true);
        $criteria->compare('informacion_tienda', $this->informacion_tienda, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}