<?php

/**
 * This is the model base class for the table "proveedor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Proveedor".
 *
 * Columns in table "proveedor" available as properties of the model,
 * followed by relations of table "proveedor" available as properties of the model.
 *
 * @property integer $id_proveedor
 * @property string $nombre_proveedor
 * @property string $empresa_proveedor
 * @property string $telefono
 * @property string $email
 *
 * @property Compra[] $compras
 */
abstract class BaseProveedor extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'proveedor';
    }

    public static function representingColumn() {
        return 'nombre_proveedor';
    }

    public function rules() {
        return array(
            array('id_proveedor', 'required'),
            array('id_proveedor', 'numerical', 'integerOnly'=>true),
            array('nombre_proveedor, empresa_proveedor', 'length', 'max'=>50),
            array('telefono', 'length', 'max'=>30),
            array('email', 'length', 'max'=>60),
            array('nombre_proveedor, empresa_proveedor, telefono, email', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_proveedor, nombre_proveedor, empresa_proveedor, telefono, email', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'compras' => array(self::HAS_MANY, 'Compra', 'id_proveedor'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_proveedor' => Yii::t('app', 'Id Proveedor'),
                'nombre_proveedor' => Yii::t('app', 'Nombre Proveedor'),
                'empresa_proveedor' => Yii::t('app', 'Empresa Proveedor'),
                'telefono' => Yii::t('app', 'Telefono'),
                'email' => Yii::t('app', 'Email'),
                'compras' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_proveedor', $this->id_proveedor);
        $criteria->compare('nombre_proveedor', $this->nombre_proveedor, true);
        $criteria->compare('empresa_proveedor', $this->empresa_proveedor, true);
        $criteria->compare('telefono', $this->telefono, true);
        $criteria->compare('email', $this->email, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}