<?php

/**
 * This is the model base class for the table "publicacion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Publicacion".
 *
 * Columns in table "publicacion" available as properties of the model,
 * followed by relations of table "publicacion" available as properties of the model.
 *
 * @property integer $id_publicacion
 * @property string $nombre_publicacion
 * @property string $titulo_publicacion
 * @property string $descripcion_publicacion
 * @property integer $id_producto
 * @property string $precio_publicacion
 * @property string $imagen
 *
 * @property Producto $idProducto
 */
abstract class BasePublicacion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'publicacion';
    }

    public static function representingColumn() {
        return 'nombre_publicacion';
    }

    public function rules() {
        return array(
            array('id_publicacion, id_producto', 'numerical', 'integerOnly'=>true),
            array('nombre_publicacion', 'length', 'max'=>50),
            array('titulo_publicacion, descripcion_publicacion, precio_publicacion', 'length', 'max'=>255),
            array('imagen', 'length', 'max'=>100),
            array('id_publicacion, nombre_publicacion, titulo_publicacion, descripcion_publicacion, id_producto, precio_publicacion, imagen', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_publicacion, nombre_publicacion, titulo_publicacion, descripcion_publicacion, id_producto, precio_publicacion, imagen', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'idProducto' => array(self::BELONGS_TO, 'Producto', 'id_producto'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_publicacion' => Yii::t('app', 'Id Publicacion'),
                'nombre_publicacion' => Yii::t('app', 'Nombre Publicacion'),
                'titulo_publicacion' => Yii::t('app', 'Titulo Publicacion'),
                'descripcion_publicacion' => Yii::t('app', 'Descripcion Publicacion'),
                'id_producto' => Yii::t('app', 'Id Producto'),
                'precio_publicacion' => Yii::t('app', 'Precio Publicacion'),
                'imagen' => Yii::t('app', 'Imagen'),
                'idProducto' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_publicacion', $this->id_publicacion);
        $criteria->compare('nombre_publicacion', $this->nombre_publicacion, true);
        $criteria->compare('titulo_publicacion', $this->titulo_publicacion, true);
        $criteria->compare('descripcion_publicacion', $this->descripcion_publicacion, true);
        $criteria->compare('id_producto', $this->id_producto);
        $criteria->compare('precio_publicacion', $this->precio_publicacion, true);
        $criteria->compare('imagen', $this->imagen, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}